/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdlcstudy;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author justin
 */
public class QuizForm extends javax.swing.JFrame {

    MainForm mainScreen;
    //Quiz object that stores info on the quiz
    private Quiz quiz;
    //button array to control answers to the quiz
    private JRadioButton[] answers = new JRadioButton[4];
    private int numCorrect;
    private int numAnswered;
    private int currentQuestion;

    /**
     * Creates a new quiz form
     *
     * @param m Main form so we can switch visible frames
     */
    public QuizForm(MainForm m) {
        initComponents();
        //initialize all variables
        numCorrect = 0;
        numAnswered = 0;
        mainScreen = m;
        quiz = new Quiz();
        answers[0] = jBtnOption1;
        answers[1] = jBtnOption2;
        answers[2] = jBtnOption3;
        answers[3] = jBtnOption4;
        btnNext.setEnabled(false);
        currentQuestion = 0;
        displayQuestion(currentQuestion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupOptions = new javax.swing.ButtonGroup();
        btnMain = new javax.swing.JButton();
        jBtnOption1 = new javax.swing.JRadioButton();
        jBtnOption2 = new javax.swing.JRadioButton();
        jBtnOption3 = new javax.swing.JRadioButton();
        jBtnOption4 = new javax.swing.JRadioButton();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        lblCorrectPrompt = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblAnsweredPrompt = new javax.swing.JLabel();
        lblAnswered = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblCorrectAnswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMain.setText("Main Screen");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        btnGroupOptions.add(jBtnOption1);
        jBtnOption1.setSelected(true);

        btnGroupOptions.add(jBtnOption2);

        btnGroupOptions.add(jBtnOption3);

        btnGroupOptions.add(jBtnOption4);

        lblA.setText("A.");

        lblB.setText("B.");

        lblC.setText("C.");

        lblD.setText("D.");

        btnSubmit.setText("Submit Answer");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCorrectPrompt.setText("Correct Questions:");

        lblCorrect.setText("0");

        lblAnsweredPrompt.setText("Answered Questions:");

        lblAnswered.setText("0");

        jLabel1.setText("Correct Answer:");

        btnNext.setText("Next Question");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(31, 31, 31)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(btnMain))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblB)
                            .addComponent(lblC)
                            .addComponent(lblD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnOption3)
                                    .addComponent(jBtnOption4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnOption1)
                                    .addComponent(jBtnOption2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnsweredPrompt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCorrectPrompt, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnswered)
                                    .addComponent(lblCorrect))
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuestion)
                            .addComponent(lblA)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblCorrectAnswer)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnOption1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblA, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnOption2)
                            .addComponent(lblB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnOption3)
                            .addComponent(lblC))
                        .addGap(21, 21, 21)
                        .addComponent(jBtnOption4))
                    .addComponent(lblD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorrectPrompt)
                            .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnsweredPrompt)
                            .addComponent(lblAnswered))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCorrectAnswer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMain)
                    .addComponent(btnSubmit)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        //hide this form
        this.setVisible(false);
        //reset this form so that on return everything is displayed from the start
        numCorrect = 0;
        numAnswered = 0;
        currentQuestion = 0;
        lblCorrect.setText("0");
        lblAnswered.setText("0");
        lblCorrectAnswer.setText("");
        btnNext.setEnabled(false);
        btnSubmit.setEnabled(true);
        //set the main screen form visible
        mainScreen.setVisible(true);

    }//GEN-LAST:event_btnMainActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        int userChoice = 0;
        for (int i = 0; i < 4; i++) {
            //get selected answer
            if (answers[i].isSelected()) {
                //since correct answers range from 1-4 inclusive, increase i by one, as i ranges from 0-3 inclusive
                userChoice = i + 1;
                //stop looping through the buttons
                i = 4;
            }
        }
        //check if the user answered correctly
        if (userChoice == quiz.getCorrectAnswer(currentQuestion)) {
            numCorrect++;
            numAnswered++;
        } else {
            numAnswered++;
        }

        //display data for user about the quiz
        lblCorrect.setText("" + numCorrect);
        lblAnswered.setText("" + numAnswered);
        lblCorrectAnswer.setText(quiz.getAnswers(currentQuestion)[quiz.getCorrectAnswer(currentQuestion) - 1]);
        //enable the next question button and disable the submit button
        btnNext.setEnabled(true);
        btnSubmit.setEnabled(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        //only display the next question if there are questions left
        if (currentQuestion < 9) {
            currentQuestion++;
            displayQuestion(currentQuestion);
            btnNext.setEnabled(false);
            lblCorrectAnswer.setText("");
            btnSubmit.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "You answered " + numCorrect + " correct out of " + numAnswered + ""
                    + " questions");
            //hide this form
            this.setVisible(false);
            //set the main screen form visible
            mainScreen.setVisible(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed
    /**
     *
     * @param i question to display
     */
    public void displayQuestion(int i) {
        //Display the question
        lblQuestion.setText(quiz.getQuestion(i));
        //get the answers to the question
        String qAnswers[] = quiz.getAnswers(i);
        //display the answers
        for (int j = 0; j < 4; j++) {
            answers[j].setText(qAnswers[j]);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOptions;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton jBtnOption1;
    private javax.swing.JRadioButton jBtnOption2;
    private javax.swing.JRadioButton jBtnOption3;
    private javax.swing.JRadioButton jBtnOption4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAnswered;
    private javax.swing.JLabel lblAnsweredPrompt;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectAnswer;
    private javax.swing.JLabel lblCorrectPrompt;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
